### ISSUE TITLE
Move to a GitHub org instead of personal repo

### ISSUE THREAD

**Issue by davidebbo** [ReflectionMagic/ReflectionMagic#27]
@jvandertil I think we should just do it. One pattern is to simply name the org the same as the repo. So it would be ReflectionMagic/ReflectionMagic.

**Comment by davidebbo** [comment]
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

If you're good with that, I can just do it.

**Comment by jvandertil** [comment]
Sounds good, I think ReflectionMagic/ReflectionMagic would work just fine :)

**Comment by davidebbo** [comment]
Ok, done deal. You should have received an invite for the org.

**Comment by davidebbo** [comment]
They really make this easy. Someone should buy this company :)
