### ISSUE TITLE
Is there a possibility to set auto generated backing fields?

### ISSUE THREAD

**Issue by TFTomSun** [ReflectionMagic/ReflectionMagic#33]
Lets assume I want to set a read only property with the name Path. The compiler generates a backing field name with something like:
<Path>k__BackingField

of course these brackets can't be used to set the field using dynamic coding. Do you have some code conventions that allow me to set that backing field?

**Comment by jvandertil** [comment]
No, unfortunately we currently do not support the setting of automatically generated backing fields through the dynamic API.

Using some code from [this](https://stackoverflow.com/questions/8817070/is-it-possible-to-access-backing-fields-behind-auto-implemented-properties) StackOverflow answer, and the API I marked deprecated (seemed more like an accidental exposure of an internal API), you could do something like this:

```cs
private string GetBackingFieldName(string propertyName)
{
    return string.Format("<{0}>k__BackingField", propertyName);
}

private FieldInfo GetBackingField(object obj, string propertyName)
{
    return obj.GetType().GetField(GetBackingFieldName(propertyName), BindingFlags.Instance | BindingFlags.NonPublic);
}

// ....

GetBackingField(obj, "Path").ToIProperty().SetValue(obj, "NewValue", null);
```

But I think you've already figured that out, and I don't think that converting to IProperty adds much value for you.

I'm not sure if I would be willing to add searching for an auto generated backing field when no setter on a property is found, need to think about the implications when adding that.

**Comment by TFTomSun** [comment]
you could make it configurable in the AsDynamic() extension. e. g. AsDynamic(bool fallbackToPropertyBackingFields)

**Comment by davidebbo** [comment]
This seems like a good addition. The whole hard coding `k__BackingField` is a hack, but then again, this whole project is a happy hack! 😆
